name: FedRAMP SCN Detection

# Trigger on PR to paths containing Infrastructure as Code
on:
  pull_request:
    paths:
      - 'terraform/**'
      - 'infrastructure/**'
      - 'kubernetes/**'
      - 'cloudformation/**'
      - '.github/scn-config.yml'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  scn-detection:
    name: FedRAMP SCN Analysis
    runs-on: ubuntu-latest

    steps:
      # Checkout with full history for git diff
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Required for SCN detector to analyze changes

      # Run SCN detector
      - name: Analyze IaC changes for FedRAMP SCN
        id: scn
        uses: huntridge-labs/argus/.github/actions/scn-detector@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}  # Optional: for AI fallback
        with:
          config_file: '.github/scn-config.yml'
          create_issues: true       # Create GitHub Issues for tracking
          post_pr_comment: true     # Post PR comment with analysis
          enable_ai_fallback: true  # Use AI for ambiguous cases
          fail_on_category: 'none'  # Don't fail workflow on any category

      # Example: Conditional workflow based on SCN category
      - name: Notify team for transformative changes
        if: steps.scn.outputs.transformative_count > 0 || steps.scn.outputs.impact_count > 0
        run: |
          echo "⚠️ Transformative or Impact changes detected!"
          echo "Transformative: ${{ steps.scn.outputs.transformative_count }}"
          echo "Impact: ${{ steps.scn.outputs.impact_count }}"
          echo "Issues created: ${{ steps.scn.outputs.issue_numbers }}"

      # Example: Display analysis results
      - name: Display SCN analysis results
        if: always()
        run: |
          echo "📊 SCN Analysis Summary:"
          echo "  Category: ${{ steps.scn.outputs.change_category }}"
          echo "  Routine: ${{ steps.scn.outputs.routine_count }}"
          echo "  Adaptive: ${{ steps.scn.outputs.adaptive_count }}"
          echo "  Transformative: ${{ steps.scn.outputs.transformative_count }}"
          echo "  Impact: ${{ steps.scn.outputs.impact_count }}"
          echo "  Has Changes: ${{ steps.scn.outputs.has_changes }}"

---

# Example: Separate workflow with failure threshold
name: FedRAMP SCN Detection (Strict)

on:
  pull_request:
    branches:
      - main
      - production
    paths:
      - 'terraform/**'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  scn-detection-strict:
    name: SCN Analysis (Fail on Impact)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: huntridge-labs/argus/.github/actions/scn-detector@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config_file: '.github/scn-config.yml'
          create_issues: true
          post_pr_comment: true
          enable_ai_fallback: false  # Rule-based only for deterministic behavior
          fail_on_category: 'impact'  # ❌ Fail workflow if impact changes detected

---

# Example: Scheduled SCN analysis for main branch
name: FedRAMP SCN Weekly Audit

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM UTC
  workflow_dispatch:     # Manual trigger

permissions:
  contents: read
  issues: write

jobs:
  weekly-scn-audit:
    name: Weekly SCN Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Compare last week's changes
      - name: Analyze week's changes
        uses: huntridge-labs/argus/.github/actions/scn-detector@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        with:
          base_ref: 'HEAD~7'  # 7 days ago (approximate)
          head_ref: 'HEAD'    # Current
          config_file: '.github/scn-config.yml'
          create_issues: true
          post_pr_comment: false  # No PR to comment on
          enable_ai_fallback: true

---

# Example: Multi-repository analysis
name: Multi-Repo SCN Analysis

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Target repository to analyze (org/repo)'
        required: true
        type: string

permissions:
  contents: read
  issues: write

jobs:
  cross-repo-scn:
    name: Cross-Repository SCN
    runs-on: ubuntu-latest

    steps:
      # Checkout target repository
      - name: Checkout target repository
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.target_repo }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Checkout shared SCN config from this repo
      - name: Checkout SCN config
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          path: 'scn-config-repo'
          sparse-checkout: |
            .github/scn-config.yml

      # Analyze with shared config
      - name: Analyze with shared config
        uses: huntridge-labs/argus/.github/actions/scn-detector@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config_file: 'scn-config-repo/.github/scn-config.yml'
          create_issues: true
          post_pr_comment: false
