name: 'Linting Summary'
description: |
  Aggregate all linter results into a unified report.

  This action is designed to run as the FINAL job in your linting workflow,
  after all linter jobs have completed. It automatically discovers and combines
  summaries from all linters into a formatted GitHub Step Summary.

  **Required Environment Variables:**
  - GITHUB_TOKEN: GitHub token for API access (set automatically in workflows)

  **Usage Example:**
  ```yaml
  linting-summary:
    runs-on: ubuntu-latest
    needs: [yaml-lint, json-lint, python-lint, javascript-lint, dockerfile-lint, terraform-lint]
    if: always()
    steps:
      - uses: huntridge-labs/argus/.github/actions/linting-summary@main
  ```

  **Important:**
  - Add this job AFTER all your linter jobs
  - List all linter jobs in the 'needs' field
  - Use 'if: always()' to ensure it runs even if linters fail
  - Use 'continue-on-error: true' on linter jobs so they don't block the summary

inputs:
  summary_pattern:
    description: 'Artifact pattern to match linter summaries'
    required: false
    default: 'linter-summary-*'
  title:
    description: 'Title for the summary report'
    required: false
    default: 'Code Quality & Linting Summary'
  show_metadata:
    description: 'Show workflow metadata (run number, branch, commit)'
    required: false
    default: 'true'
  show_stats:
    description: 'Show statistics about linter results'
    required: false
    default: 'true'
  post_pr_comment:
    description: 'Post combined summary as PR comment'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Download all linter summaries
      uses: actions/download-artifact@v6
      with:
        pattern: ${{ inputs.summary_pattern }}
        path: linter-summaries
        merge-multiple: true
      continue-on-error: true

    - name: Generate combined summary
      shell: bash
      run: |
        # Create output directory for PR comment file
        mkdir -p combined-summaries

        # Function to generate summary content
        generate_summary() {
          local output="$1"
          local include_title="$2"

          if [ "$include_title" = "true" ]; then
            echo "## ${{ inputs.title }}" >> "$output"
            echo "" >> "$output"
          fi

          # Show metadata if enabled
          if [ "${{ inputs.show_metadata }}" = "true" ]; then
            echo "**Workflow Run:** [${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> "$output"

            # Use head_ref for PRs (source branch), ref_name for pushes
            BRANCH_NAME="${{ github.head_ref }}"
            if [ -z "$BRANCH_NAME" ]; then
              BRANCH_NAME="${{ github.ref_name }}"
            fi
            echo "**Branch:** \`$BRANCH_NAME\`" >> "$output"

            echo "**Commit:** [\`${GITHUB_SHA:0:7}\`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})" >> "$output"
            echo "" >> "$output"
          fi

          # Check if we have any linter summaries
          if [ -d "linter-summaries" ] && [ "$(ls -A linter-summaries 2>/dev/null)" ]; then
            LINTER_COUNT=$(find linter-summaries -name "*.md" -type f | wc -l)

            # Show stats if enabled
            if [ "${{ inputs.show_stats }}" = "true" ]; then
              echo "**Linters Executed:** $LINTER_COUNT" >> "$output"
              echo "" >> "$output"
            fi

            echo "### Linter Results" >> "$output"
            echo "" >> "$output"

            # Combine all linter summaries in alphabetical order
            for summary in $(find linter-summaries -name "*.md" -type f | sort); do
              if [ -f "$summary" ]; then
                cat "$summary" >> "$output"
              fi
            done
          else
            echo "**No linter summaries found**" >> "$output"
            echo "" >> "$output"
            echo "This could mean:" >> "$output"
            echo "- No linters were executed" >> "$output"
            echo "- Linter jobs failed before generating summaries" >> "$output"
            echo "- Artifacts did not upload correctly" >> "$output"
            echo "" >> "$output"
            echo "Check the job logs for more details." >> "$output"
          fi

          echo "" >> "$output"
          echo "---" >> "$output"
          echo "_Generated by [Argus](https://github.com/huntridge-labs/hardening-workflows)_" >> "$output"
        }

        # Generate job summary (with title)
        generate_summary "$GITHUB_STEP_SUMMARY" "true"

        # Generate PR comment file (without title - comment-pr adds it)
        generate_summary "combined-summaries/linting.md" "false"
      continue-on-error: true

    - name: Comment PR with linting summary
      if: github.event_name == 'pull_request' && inputs.post_pr_comment == 'true'
      uses: huntridge-labs/argus/.github/actions/comment-pr@main
      with:
        summary_file: combined-summaries/linting.md
        comment_marker: linting-summary-comment-marker
        title: '${{ inputs.title }}'
        fallback_message: 'No linter results available'

branding:
  icon: 'file-text'
  color: 'green'
