"""
Integration tests for the security-summary action aggregation pattern.

The security-summary action downloads individual scanner summary markdown
files and combines them into a unified report. These tests simulate that
flow by creating mock scanner summaries, combining them following the
same logic as the action's bash script, and validating the output.
"""

from pathlib import Path

import pytest


def _generate_combined_summary(
    scanner_summaries_dir: Path,
    output_file: Path,
    title: str = "Security Scan Summary",
    show_metadata: bool = False,
    show_stats: bool = True,
):
    """Reproduce the core aggregation logic from security-summary/action.yml.

    This mirrors the bash generate_summary() function: discover *.md files
    in the summaries directory, count them, concatenate in sorted order,
    and write a combined report.
    """
    lines = []

    lines.append(title)
    lines.append("")

    md_files = sorted(scanner_summaries_dir.glob("*.md")) if scanner_summaries_dir.exists() else []

    if md_files:
        if show_stats:
            lines.append(f"**Scanners Executed:** {len(md_files)}")
            lines.append("")

        lines.append("### Scanner Results")
        lines.append("")

        for md_file in md_files:
            lines.append(md_file.read_text())
    else:
        lines.append("**No scanner summaries found**")
        lines.append("")
        lines.append("This could mean:")
        lines.append("- No scanners were executed")
        lines.append("- Scanner jobs failed before generating summaries")
        lines.append("- Artifacts did not upload correctly")
        lines.append("")
        lines.append("Check the job logs for more details.")

    lines.append("")
    lines.append("---")
    lines.append("_Generated by [Argus](https://github.com/huntridge-labs/argus)_")

    output_file.write_text("\n".join(lines))


# Sample scanner summary content used across tests
BANDIT_SUMMARY = """\
#### Bandit (Python SAST)

| Severity | Count |
|----------|-------|
| Critical | 0     |
| High     | 2     |
| Medium   | 1     |
| Low      | 0     |

**Total findings:** 3
"""

GITLEAKS_SUMMARY = """\
#### Gitleaks (Secret Detection)

| Severity | Count |
|----------|-------|
| Critical | 1     |
| High     | 0     |

**Total findings:** 1
"""

TRIVY_IAC_SUMMARY = """\
#### Trivy IaC

| Severity | Count |
|----------|-------|
| Critical | 0     |
| High     | 1     |
| Medium   | 3     |
| Low      | 2     |

**Total findings:** 6
"""


class TestSecuritySummaryAggregation:
    """Test the scanner-summary aggregation pattern end-to-end."""

    @pytest.mark.integration
    def test_combines_all_scanner_summaries(self, tmp_path):
        """All scanner markdown files are included in the combined output."""
        summaries_dir = tmp_path / "scanner-summaries"
        summaries_dir.mkdir()
        (summaries_dir / "bandit.md").write_text(BANDIT_SUMMARY)
        (summaries_dir / "gitleaks.md").write_text(GITLEAKS_SUMMARY)
        (summaries_dir / "trivy-iac.md").write_text(TRIVY_IAC_SUMMARY)

        output = tmp_path / "security.md"
        _generate_combined_summary(summaries_dir, output)

        content = output.read_text()
        assert "Bandit" in content, "Missing Bandit section"
        assert "Gitleaks" in content, "Missing Gitleaks section"
        assert "Trivy IaC" in content, "Missing Trivy IaC section"

    @pytest.mark.integration
    def test_scanner_count_is_correct(self, tmp_path):
        """Stats line reports the correct number of scanners."""
        summaries_dir = tmp_path / "scanner-summaries"
        summaries_dir.mkdir()
        (summaries_dir / "bandit.md").write_text(BANDIT_SUMMARY)
        (summaries_dir / "gitleaks.md").write_text(GITLEAKS_SUMMARY)

        output = tmp_path / "security.md"
        _generate_combined_summary(summaries_dir, output)

        content = output.read_text()
        assert "**Scanners Executed:** 2" in content

    @pytest.mark.integration
    def test_summaries_sorted_alphabetically(self, tmp_path):
        """Scanner summaries appear in alphabetical filename order."""
        summaries_dir = tmp_path / "scanner-summaries"
        summaries_dir.mkdir()
        (summaries_dir / "zap.md").write_text("#### ZAP\nfindings: 0\n")
        (summaries_dir / "bandit.md").write_text(BANDIT_SUMMARY)

        output = tmp_path / "security.md"
        _generate_combined_summary(summaries_dir, output)

        content = output.read_text()
        bandit_pos = content.index("Bandit")
        zap_pos = content.index("ZAP")
        assert bandit_pos < zap_pos, "Bandit should appear before ZAP (alphabetical order)"

    @pytest.mark.integration
    def test_missing_summaries_directory_handled(self, tmp_path):
        """When the summaries directory does not exist, a fallback message is shown."""
        summaries_dir = tmp_path / "scanner-summaries"  # not created
        output = tmp_path / "security.md"

        _generate_combined_summary(summaries_dir, output)

        content = output.read_text()
        assert "**No scanner summaries found**" in content
        assert "No scanners were executed" in content

    @pytest.mark.integration
    def test_empty_summaries_directory_handled(self, tmp_path):
        """An empty summaries directory produces the fallback message."""
        summaries_dir = tmp_path / "scanner-summaries"
        summaries_dir.mkdir()

        output = tmp_path / "security.md"
        _generate_combined_summary(summaries_dir, output)

        content = output.read_text()
        assert "**No scanner summaries found**" in content

    @pytest.mark.integration
    def test_output_contains_footer(self, tmp_path):
        """Combined output always ends with the Argus attribution footer."""
        summaries_dir = tmp_path / "scanner-summaries"
        summaries_dir.mkdir()
        (summaries_dir / "bandit.md").write_text(BANDIT_SUMMARY)

        output = tmp_path / "security.md"
        _generate_combined_summary(summaries_dir, output)

        content = output.read_text()
        assert "---" in content
        assert "_Generated by [Argus]" in content

    @pytest.mark.integration
    def test_output_contains_title(self, tmp_path):
        """Combined output starts with the configured title."""
        summaries_dir = tmp_path / "scanner-summaries"
        summaries_dir.mkdir()
        (summaries_dir / "bandit.md").write_text(BANDIT_SUMMARY)

        output = tmp_path / "security.md"
        _generate_combined_summary(summaries_dir, output, title="Custom Title")

        content = output.read_text()
        assert content.startswith("Custom Title")

    @pytest.mark.integration
    def test_stats_hidden_when_disabled(self, tmp_path):
        """Scanner count line is omitted when show_stats is False."""
        summaries_dir = tmp_path / "scanner-summaries"
        summaries_dir.mkdir()
        (summaries_dir / "bandit.md").write_text(BANDIT_SUMMARY)

        output = tmp_path / "security.md"
        _generate_combined_summary(summaries_dir, output, show_stats=False)

        content = output.read_text()
        assert "**Scanners Executed:**" not in content
        assert "Bandit" in content

    @pytest.mark.integration
    def test_single_scanner_summary(self, tmp_path):
        """Works correctly with just one scanner summary."""
        summaries_dir = tmp_path / "scanner-summaries"
        summaries_dir.mkdir()
        (summaries_dir / "gitleaks.md").write_text(GITLEAKS_SUMMARY)

        output = tmp_path / "security.md"
        _generate_combined_summary(summaries_dir, output)

        content = output.read_text()
        assert "**Scanners Executed:** 1" in content
        assert "Gitleaks" in content
        assert "### Scanner Results" in content

    @pytest.mark.integration
    def test_markdown_tables_preserved(self, tmp_path):
        """Markdown table formatting from individual scanners is preserved."""
        summaries_dir = tmp_path / "scanner-summaries"
        summaries_dir.mkdir()
        (summaries_dir / "bandit.md").write_text(BANDIT_SUMMARY)

        output = tmp_path / "security.md"
        _generate_combined_summary(summaries_dir, output)

        content = output.read_text()
        assert "| Severity | Count |" in content
        assert "|----------|-------|" in content


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
