"""Unit tests for argus.core.sbom — SBOM format detection."""

from __future__ import annotations

import json

import pytest

from argus.core.sbom import (
    SbomDetectionError,
    SbomInfo,
    detect_sbom,
)


class TestDetectSbomFormats:
    def test_cyclonedx_json(self, tmp_path):
        f = tmp_path / "sbom.json"
        f.write_text(json.dumps({
            "bomFormat": "CycloneDX",
            "specVersion": "1.5",
            "components": [],
        }))
        info = detect_sbom(f)
        assert info.format == "cyclonedx-json"
        assert info.display_format == "CycloneDX JSON"

    def test_cyclonedx_xml(self, tmp_path):
        f = tmp_path / "sbom.xml"
        f.write_text(
            '<?xml version="1.0"?>\n'
            '<bom xmlns="http://cyclonedx.org/schema/bom/1.5" version="1"/>'
        )
        info = detect_sbom(f)
        assert info.format == "cyclonedx-xml"

    def test_spdx_json(self, tmp_path):
        f = tmp_path / "sbom.spdx.json"
        f.write_text(json.dumps({
            "spdxVersion": "SPDX-2.3",
            "SPDXID": "SPDXRef-DOCUMENT",
            "packages": [],
        }))
        info = detect_sbom(f)
        assert info.format == "spdx-json"

    def test_spdx_tag_value(self, tmp_path):
        f = tmp_path / "sbom.spdx"
        f.write_text(
            "SPDXVersion: SPDX-2.3\n"
            "DataLicense: CC0-1.0\n"
            "DocumentName: example\n"
        )
        info = detect_sbom(f)
        assert info.format == "spdx-tv"

    def test_syft_json_preferred_over_cyclonedx(self, tmp_path):
        # Syft-produced CycloneDX JSON still carries a descriptor.name == syft
        # — we prefer syft detection so downstream tooling can take advantage.
        f = tmp_path / "syft.json"
        f.write_text(json.dumps({
            "descriptor": {"name": "syft", "version": "1.0"},
            "bomFormat": "CycloneDX",
            "specVersion": "1.5",
        }))
        info = detect_sbom(f)
        assert info.format == "syft-json"

    def test_comments_before_spdx_version(self, tmp_path):
        f = tmp_path / "sbom.spdx"
        f.write_text(
            "# Generated by foo\n"
            "\n"
            "SPDXVersion: SPDX-2.3\n"
        )
        info = detect_sbom(f)
        assert info.format == "spdx-tv"


class TestDetectSbomErrors:
    def test_missing_file(self, tmp_path):
        with pytest.raises(SbomDetectionError, match="not found"):
            detect_sbom(tmp_path / "nope.json")

    def test_unrecognized_json(self, tmp_path):
        f = tmp_path / "sbom.json"
        f.write_text(json.dumps({"something": "else"}))
        with pytest.raises(SbomDetectionError, match="Unrecognized"):
            detect_sbom(f)

    def test_unrecognized_xml(self, tmp_path):
        f = tmp_path / "plain.xml"
        f.write_text('<?xml version="1.0"?>\n<rootelement/>')
        with pytest.raises(SbomDetectionError):
            detect_sbom(f)

    def test_unrecognized_text(self, tmp_path):
        f = tmp_path / "notes.txt"
        f.write_text("This is just a text file.")
        with pytest.raises(SbomDetectionError):
            detect_sbom(f)

    def test_malformed_json_is_rejected(self, tmp_path):
        f = tmp_path / "broken.json"
        f.write_text('{"bomFormat": "CycloneDX", ')  # truncated
        with pytest.raises(SbomDetectionError):
            detect_sbom(f)


class TestSbomInfo:
    def test_display_format_falls_back_to_raw(self, tmp_path):
        info = SbomInfo(path=tmp_path / "x", format="custom-thing")
        assert info.display_format == "custom-thing"
