"""Tests for argus.preflight.report_body."""

from argus.preflight.report_body import build_issue_body, is_all_healthy, ToolStatus


class TestBuildIssueBody:
    """Test Markdown body generation for the living issue."""

    def test_healthy_body(self):
        body = build_issue_body("argus.yml", [], [], [])
        assert "## Argus Config Health" in body
        assert "`argus.yml`" in body
        assert "auto-closed" in body

    def test_errors_section(self):
        body = build_issue_body("argus.yml", ["bad key 'foo'"], [], [])
        assert "### Errors" in body
        assert "bad key 'foo'" in body

    def test_warnings_section(self):
        body = build_issue_body("argus.yml", [], ["unknown scanner 'baz'"], [])
        assert "### Warnings" in body
        assert "unknown scanner 'baz'" in body

    def test_tool_readiness_table(self):
        statuses = [
            ToolStatus("bandit", True, "local"),
            ToolStatus("osv", True, "container", "ghcr.io/google/osv-scanner:v2.3.5", ["OSV API"]),
            ToolStatus("zap", False, "none"),
        ]
        body = build_issue_body("argus.yml", [], [], statuses)
        assert "### Tool Readiness" in body
        assert "| bandit |" in body
        assert "| osv |" in body
        assert "**unavailable**" in body
        assert "OSV API" in body

    def test_container_image_in_method(self):
        statuses = [ToolStatus("trivy", True, "container", "aquasec/trivy:0.69.3")]
        body = build_issue_body("argus.yml", [], [], statuses)
        assert "aquasec/trivy:0.69.3" in body

    def test_footer(self):
        body = build_issue_body("argus.yml", [], [], [])
        assert "Generated by Argus CLI" in body

    def test_timestamp_present(self):
        body = build_issue_body("argus.yml", [], [], [])
        assert "Last checked:" in body

    def test_no_autoclose_when_errors(self):
        body = build_issue_body("argus.yml", ["error"], [], [])
        assert "auto-closed" not in body


class TestIsAllHealthy:
    """Test the health determination logic."""

    def test_no_issues(self):
        assert is_all_healthy([], [], []) is True

    def test_errors_unhealthy(self):
        assert is_all_healthy(["err"], [], []) is False

    def test_unavailable_tools_unhealthy(self):
        assert is_all_healthy([], [], ["zap"]) is False

    def test_warnings_healthy_without_strict(self):
        assert is_all_healthy([], ["warn"], []) is True

    def test_warnings_unhealthy_with_strict(self):
        assert is_all_healthy([], ["warn"], [], strict=True) is False

    def test_all_bad(self):
        assert is_all_healthy(["err"], ["warn"], ["zap"], strict=True) is False
