"""Generate Markdown body for the Argus Config Health living issue."""

from __future__ import annotations

import datetime
from dataclasses import dataclass, field


@dataclass
class ToolStatus:
    """Status of a single scanner's tool readiness."""

    name: str
    available: bool
    method: str             # "local", "container", "none"
    image: str | None = None
    network_deps: list[str] = field(default_factory=list)


def build_issue_body(
    config_path: str,
    errors: list[str],
    warnings: list[str],
    tool_statuses: list[ToolStatus] | None = None,
) -> str:
    """Build the Markdown body for the living issue.

    The body is designed to be fully replaced on each update,
    preserving the issue's comment history while keeping the
    body current.
    """
    now = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "## Argus Config Health",
        "",
        f"> Last checked: {now}",
        f"> Config: `{config_path}`",
        "",
    ]

    if errors:
        lines.append("### Errors")
        lines.append("")
        for e in errors:
            lines.append(f"- {e}")
        lines.append("")

    if warnings:
        lines.append("### Warnings")
        lines.append("")
        for w in warnings:
            lines.append(f"- {w}")
        lines.append("")

    if tool_statuses:
        lines.append("### Tool Readiness")
        lines.append("")
        lines.append("| Scanner | Status | Method | Network Deps |")
        lines.append("|---------|--------|--------|-------------|")
        for t in tool_statuses:
            status = "available" if t.available else "**unavailable**"
            deps = ", ".join(t.network_deps) if t.network_deps else "none"
            method = t.method
            if t.image and t.method == "container":
                method = f"container (`{t.image}`)"
            lines.append(f"| {t.name} | {status} | {method} | {deps} |")
        lines.append("")

    if not errors and not warnings and not any(
        not t.available for t in (tool_statuses or [])
    ):
        lines.append("All checks pass. This issue will be auto-closed.")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Argus CLI — this issue is updated automatically.*")

    return "\n".join(lines)


def is_all_healthy(
    errors: list[str],
    warnings_strict: list[str],
    unavailable_tools: list[str],
    strict: bool = False,
) -> bool:
    """Determine if all checks pass (issue should be closed).

    Args:
        errors: fatal config errors
        warnings_strict: config warnings (only counted in strict mode)
        unavailable_tools: scanner names that can't run
        strict: whether warnings count as failures
    """
    if errors:
        return False
    if unavailable_tools:
        return False
    if strict and warnings_strict:
        return False
    return True
