name: 'Security Summary'
description: |
  Aggregate all security scan results into a unified report.

  This action is designed to run as the FINAL job in your security workflow, after all scanner
  jobs have completed. It automatically discovers and combines summaries from all security
  scanners into a formatted GitHub Step Summary.

  **Required Environment Variables:**
  - GITHUB_TOKEN: GitHub token for API access (set automatically in workflows)

  **Usage Example:**
  ```yaml
  security-summary:
    runs-on: ubuntu-latest
    needs: [bandit-scan, gitleaks-scan, trivy-iac-scan, clamav-scan]
    if: always()
    steps:
      - uses: huntridge-labs/argus/.github/actions/security-summary@0.4.0
  ```

  **Important:**
  - Add this job AFTER all your scanner jobs
  - List all scanner jobs in the 'needs' field
  - Use 'if: always()' to ensure it runs even if scanners fail
  - Use 'continue-on-error: true' on scanner jobs so they don't block the summary

inputs:
  summary_pattern:
    description: 'Artifact pattern to match scanner summaries'
    required: false
    default: 'scanner-summary-*'
  title:
    description: 'Title for the summary report'
    required: false
    default: '🔒 Security Scan Summary'
  show_metadata:
    description: 'Show workflow metadata (run number, branch, commit)'
    required: false
    default: 'true'
  show_stats:
    description: 'Show statistics about scanner results'
    required: false
    default: 'true'
  post_pr_comment:
    description: 'Post combined summary as PR comment'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Download all scanner summaries
      uses: actions/download-artifact@v6
      with:
        pattern: ${{ inputs.summary_pattern }}
        path: scanner-summaries
        merge-multiple: true
      continue-on-error: true

    - name: Generate combined summary
      shell: bash
      run: |
        # Create output directory for PR comment file
        mkdir -p combined-summaries

        # Function to generate summary content
        generate_summary() {
          local output="$1"
          local include_title="$2"

          if [ "$include_title" = "true" ]; then
            echo "${{ inputs.title }}" >> "$output"
            echo "" >> "$output"
          fi

          # Show metadata if enabled
          if [ "${{ inputs.show_metadata }}" = "true" ]; then
            echo "**Workflow Run:** [${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> "$output"

            # Use head_ref for PRs (source branch), ref_name for pushes
            BRANCH_NAME="${{ github.head_ref }}"
            if [ -z "$BRANCH_NAME" ]; then
              BRANCH_NAME="${{ github.ref_name }}"
            fi
            echo "**Branch:** \`$BRANCH_NAME\`" >> "$output"

            echo "**Commit:** [\`${GITHUB_SHA:0:7}\`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})" >> "$output"
            echo "" >> "$output"
          fi

          # Check if we have any scanner summaries
          if [ -d "scanner-summaries" ] && [ "$(ls -A scanner-summaries 2>/dev/null)" ]; then
            SCANNER_COUNT=$(find scanner-summaries -name "*.md" -type f | wc -l)

            # Show stats if enabled
            if [ "${{ inputs.show_stats }}" = "true" ]; then
              echo "**Scanners Executed:** $SCANNER_COUNT" >> "$output"
              echo "" >> "$output"
            fi

            echo "### Scanner Results" >> "$output"
            echo "" >> "$output"

            # Combine all scanner summaries in alphabetical order
            for summary in $(find scanner-summaries -name "*.md" -type f | sort); do
              if [ -f "$summary" ]; then
                cat "$summary" >> "$output"
              fi
            done
          else
            echo "**No scanner summaries found**" >> "$output"
            echo "" >> "$output"
            echo "This could mean:" >> "$output"
            echo "- No scanners were executed" >> "$output"
            echo "- Scanner jobs failed before generating summaries" >> "$output"
            echo "- Artifacts did not upload correctly" >> "$output"
            echo "" >> "$output"
            echo "Check the job logs for more details." >> "$output"
          fi

          echo "" >> "$output"
          echo "---" >> "$output"
          echo "_Generated by [Argus](https://github.com/huntridge-labs/argus)_" >> "$output"
        }

        # Generate job summary (with title)
        generate_summary "$GITHUB_STEP_SUMMARY" "true"

        # Generate PR comment file (without title - comment-pr adds it)
        generate_summary "combined-summaries/security.md" "false"
      continue-on-error: true

    - name: Comment PR with security summary
      if: github.event_name == 'pull_request' && inputs.post_pr_comment == 'true'
      uses: huntridge-labs/argus/.github/actions/comment-pr@0.4.0
      with:
        summary_file: combined-summaries/security.md
        comment_marker: security-summary-comment-marker
        title: '${{ inputs.title }}'
        fallback_message: 'No security scan results available'

branding:
  icon: 'file-text'
  color: 'blue'
