version: "1.0"
name: "FedRAMP Low Impact Level"
description: |
  Classification rules for FedRAMP Low impact systems. This profile provides
  baseline rules for detecting significant changes in low-impact cloud systems.
compliance_framework: "FedRAMP 20X"
impact_level: "Low"

# FedRAMP Significant Change Notification Categories
# - ROUTINE: No notification required (maintenance, patches, minor changes)
# - ADAPTIVE: Notification within 10 business days after completion
# - TRANSFORMATIVE: 30 days initial + 10 days final + post-completion notice
# - IMPACT: Requires new authorization (boundary/FIPS changes)

rules:
  routine:
    - pattern: 'tags.*'
      description: 'Tag changes (metadata only)'

    - pattern: 'description'
      description: 'Description changes (documentation)'

    - resource: 'aws_instance.*.user_data'
      operation: 'modify'
      description: 'User data script updates (non-security)'

    - resource: 'aws_autoscaling_group.*.desired_capacity'
      operation: 'modify'
      description: 'Minor capacity adjustments'

  adaptive:
    - resource: 'aws_ami.*'
      operation: 'modify'
      description: 'AMI updates (patching, version updates)'

    - resource: 'aws_instance.*.instance_type'
      operation: 'modify'
      description: 'Instance type changes (like-for-like sizing)'

    - pattern: 'kubernetes.io/.*version'
      description: 'Kubernetes version updates'

    - resource: 'aws_lambda_function.*.runtime'
      operation: 'modify'
      description: 'Lambda runtime version updates (same language)'

    - resource: 'aws_db_instance.*.engine_version'
      operation: 'modify'
      description: 'Database minor version updates'

  transformative:
    - resource: 'aws_rds_.*\.engine'
      operation: 'modify'
      description: 'Database engine changes (major version or type)'

    - pattern: 'provider.*.region'
      operation: 'modify'
      description: 'Region or datacenter changes'

    - resource: 'aws_lambda_function.*'
      attribute: 'runtime'
      operation: 'create'
      description: 'New runtime capabilities'

    - resource: 'aws_bedrock.*'
      operation: 'create'
      description: 'New AI/ML service usage (AWS Bedrock)'

    - resource: 'aws_sagemaker.*'
      operation: 'create'
      description: 'New AI/ML service usage (AWS SageMaker)'

    - resource: 'azurerm_cognitive_account.*'
      operation: 'create'
      description: 'New AI/ML service usage (Azure Cognitive Services)'

    - resource: 'google_vertex_ai.*'
      operation: 'create'
      description: 'New AI/ML service usage (GCP Vertex AI)'

  impact:
    - attribute: '.*encryption.*'
      operation: 'delete|modify'
      description: 'Encryption configuration changes (security boundary)'

    - resource: 'aws_security_group.*'
      attribute: 'ingress'
      pattern: '0\.0\.0\.0/0'
      description: 'Public internet access (security boundary change)'

    - resource: 'aws_kms_key.*'
      operation: 'delete'
      description: 'KMS key deletion (encryption boundary change)'

    - resource: 'aws_vpc.*'
      operation: 'create|delete'
      description: 'Network boundary changes (new/removed VPC)'

    - pattern: '.*fips.*'
      operation: 'delete|modify'
      description: 'FIPS compliance changes (requires re-authorization)'

# AI Fallback Configuration
ai_fallback:
  enabled: true
  model: 'claude-3-haiku-20240307'
  confidence_threshold: 0.8
  max_tokens: 1024
  max_diff_chars: 1000

  # AI classification prompt template
  system_prompt: |
    You are a FedRAMP compliance expert analyzing infrastructure changes for Low impact systems.

    FedRAMP Change Categories:
    - ROUTINE: Regular maintenance, patching, minor capacity changes (no notification required)
    - ADAPTIVE: Frequent improvements with minimal security plan changes (10 days after completion)
    - TRANSFORMATIVE: Rare, significant changes altering risk profile (30 days initial + 10 days final notice)
    - IMPACT: Changes to security boundary or FIPS level (requires new assessment)

    For FedRAMP Low systems:
    - Focus on security boundary and encryption changes for IMPACT
    - AI/ML services are typically TRANSFORMATIVE
    - Infrastructure scaling and patching are typically ADAPTIVE or ROUTINE
    - Configuration changes without security implications are ROUTINE

  user_prompt_template: |
    Change Details:
    - Resource Type: {resource_type}
    - Resource Name: {resource_name}
    - Operation: {operation}
    - Attributes Changed: {attributes}
    - Diff Preview:
    {diff_snippet}

    Classify this change. Respond ONLY with valid JSON in this exact format:
    {{
      "category": "ROUTINE|ADAPTIVE|TRANSFORMATIVE|IMPACT",
      "confidence": 0.0-1.0,
      "reasoning": "Brief explanation (max 200 chars)"
    }}

# Notification Timeline Configuration (FedRAMP requirements)
notifications:
  adaptive:
    post_completion_days: 10
    description: "Submit notification within 10 business days after completion"

  transformative:
    initial_notice_days: 30
    final_notice_days: 10
    post_completion_required: true
    description: "30 days initial notice, 10 days final notice, post-completion notification"

  impact:
    requires_new_assessment: true
    description: "Requires new authorization - work with 3PAO and AO"

# Issue Template Configuration
issue_templates:
  labels:
    prefix: "scn"
    categories:
      routine: "scn:routine"
      adaptive: "scn:adaptive"
      transformative: "scn:transformative"
      impact: "scn:impact"

  checklist:
    adaptive:
      - "Change description and justification"
      - "Impact analysis completed"
      - "Testing and validation results"
      - "Post-completion notification submitted"

    transformative:
      - "Initial SCN notice submitted (30 days before)"
      - "Impact analysis and risk assessment completed"
      - "Test results and validation evidence documented"
      - "Final SCN notice submitted (10 days before)"
      - "Change executed successfully"
      - "Post-completion notification submitted"

    impact:
      - "Engage 3PAO for assessment planning"
      - "Coordinate with Authorizing Official (AO)"
      - "Submit ConMon notification"
      - "Update System Security Plan (SSP)"
      - "Complete security assessment"
      - "Obtain new Authorization to Operate (ATO)"
